### ISSUE TITLE
alltalk

### ISSUE THREAD

**Issue by OsweRRR** [Sugisakii/FPUG-AMXX#1]
https://github.com/Sugisakii/FPUG-AMXX/blob/7cd0ff4c6c1ead2fa5f3711c923d20986c16308b/pug_mod.sma#L129

metele un 2 para que los muertos hablen con los vivos

**Comment by Sugisakii** [comment]
# UPDATE!!! https://github.com/Sugisakii/FPUG-AMXX/commit/557b2566e479dd7e38713b3b0571ac8b632f1aa4
