### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by OsweRRR** [Sugisakii/FPUG-AMXX#2]
https://github.com/Sugisakii/FPUG-AMXX/blob/7cd0ff4c6c1ead2fa5f3711c923d20986c16308b/pug_mod.sma#L1331

agrégale un break para qué no siga iterando por si ya están los 10 y el server es de 32 o 15 slots, quien sabe..

**Comment by Sugisakii** [comment]
Commit https://github.com/Sugisakii/FPUG-AMXX/commit/8343220dc08310053dd3b7c48c59a67e3f18f130
